<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageReference Include="OneOf" Version="3.0.271" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChatApp.Shared.Data\ChatApp.Shared.Data.csproj" />
    <ProjectReference Include="..\ChatApp.Shared.Model\ChatApp.Shared.Model.csproj" />
  </ItemGroup>

</Project>
