name: Build Linux Container Image and Push to ACR 🧊

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: source
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: chatappcontainerregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build ./ChatApp.Web/ -t chatappcontainerregistry.azurecr.io/chatappui:latest
        docker push chatappcontainerregistry.azurecr.io/chatappui:${{ github.sha }}
