name: Build Linux Container Image and Push to ACR 🧊

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -f source/ChatApp.Web/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:latest .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:latest

    - name: Log out from Docker
      run: docker logout ${{ secrets.ACR_LOGIN_SERVER }}



# on:
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash
#         working-directory: source
#     steps:
#     - uses: actions/checkout@v2
#     - uses: azure/docker-login@v1
#       with:
#         login-server: chatappcontainerregistry.azurecr.io
#         username: ${{ secrets.REGISTRY_USERNAME }}
#         password: ${{ secrets.REGISTRY_PASSWORD }}
#     - run: |
#         docker build -f ./ChatApp.Web/Dockerfile . -t chatappcontainerregistry.azurecr.io/chatappui:latest
#         docker push chatappcontainerregistry.azurecr.io/chatappui:${{ github.sha }}
