name: Deploy Azure Functions

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  APP_LOCATION: "./source/App/ChatApp.Functions"
  DOTNET_VERSION: "9.0.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Resolve Project Dependencies Using Dotnet"
        shell: bash
        run: |
          pushd './${{ env.APP_LOCATION }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_FUNCTIONS_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_FUNCTIONS_TENANTID }}
          subscription-id: ${{ secrets.AZURE_FUNCTIONS_SUBSCRIPTIONID }}

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: "chatapp-func"
          slot-name: "Production"
          package: "${{ env.APP_LOCATION }}/output"
