name: ChatApp.Web | Continuous Deployment
 
on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'
 
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: |
            dotnet restore tests/ChatApp.IntegrationTests
            dotnet restore tests/ChatApp.UnitTests

      - name: Build
        run: |
            dotnet build tests/ChatApp.IntegrationTests --configuration Release --no-restore
            dotnet build tests/ChatApp.UnitTests --configuration Release --no-restore

      - name: Test
        run: |
            dotnet test tests/ChatApp.IntegrationTests --configuration Release --no-build
            dotnet test tests/ChatApp.UnitTests --configuration Release --no-build

  az-registry:
    name: Publish | Azure Container Registry
    runs-on: ubuntu-latest
    needs: test
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
 
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
 
    - name: Build and push Docker image
      run: |
        docker build -f source/ChatApp.Web/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:latest .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:latest
 
    - name: Log out from Docker
      run: docker logout ${{ secrets.ACR_LOGIN_SERVER }}
 